version: "3.8"

services:
  namenode:
    image: bitnami/hadoop:3.3.6
    container_name: namenode
    environment:
      - HDFS_CONF_dfs_replication=1
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "9870:9870"    # Hadoop NameNode UI
      - "9000:9000"    # HDFS RPC
    volumes:
      - namenode_data:/bitnami/hadoop
      - ./docker_data:/data

  datanode:
    image: bitnami/hadoop:3.3.6
    container_name: datanode
    environment:
      - HDFS_CONF_dfs_replication=1
      - ALLOW_EMPTY_PASSWORD=yes
      - HDFS_CONF_dfs_namenode_rpc-address=namenode:9000
    depends_on:
      - namenode
    volumes:
      - datanode_data:/bitnami/hadoop

  spark:
    build:
      context: .
      dockerfile: spark.Dockerfile
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - ALLOW_EMPTY_PASSWORD=yes
    user: "1001:1001"
    ports:
      - "8080:8080"
      - "4040:4040"
      - "18080:18080"
    depends_on:
      - namenode
    volumes:
      - ./docker_data:/data

volumes:
  namenode_data:
  datanode_data:
